"""deals table

Revision ID: 2a7fea0c9292
Revises: 55a9bbbe1d18
Create Date: 2026-09-05 20:12:57.965876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7fea0c9292'
down_revision: Union[str, Sequence[str], None] = '55a9bbbe1d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('landed_cost', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('estimate', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=True),
    sa.Column('alerted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['raw_listings.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['lego_sets.set_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_listing_id'), 'deals', ['listing_id'], unique=False)
    op.create_index(op.f('ix_deals_set_id'), 'deals', ['set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deals_set_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_listing_id'), table_name='deals')
    op.drop_table('deals')
    # ### end Alembic commands ###
