"""add raw_listings

Revision ID: 4ee7053aeb0b
Revises: 9367555cbcd9
Create Date: 2026-08-08 19:36:06.659881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ee7053aeb0b'
down_revision: Union[str, Sequence[str], None] = '9367555cbcd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_listing_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(), nullable=True),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('condition_id', sa.String(), nullable=True),
    sa.Column('buying_options', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('epid', sa.String(), nullable=True),
    sa.Column('leaf_category_id', sa.String(), nullable=False),
    sa.Column('item_web_url', sa.String(), nullable=False),
    sa.Column('image_urls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('seller_feedback_score', sa.Integer(), nullable=True),
    sa.Column('seller_feedback_percentage', sa.Numeric(), nullable=True),
    sa.Column('item_creation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('item_origin_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bid_count', sa.Integer(), nullable=True),
    sa.Column('current_bid_price', sa.Numeric(), nullable=True),
    sa.Column('item_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_pickup_only', sa.Boolean(), nullable=False),
    sa.Column('distance_miles', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alerted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_listing_id', name='uq_raw_listings_source_listing_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_listings')
    # ### end Alembic commands ###
