"""value_estimates table

Revision ID: 52d3ecda4d2f
Revises: 2a7fea0c9292
Create Date: 2026-09-06 21:13:05.890218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d3ecda4d2f'
down_revision: Union[str, Sequence[str], None] = '2a7fea0c9292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('value_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('sales_volume', sa.Integer(), nullable=True),
    sa.Column('pc_id', sa.Integer(), nullable=True),
    sa.Column('sampled_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['lego_sets.set_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_id', 'bucket', 'source', 'sampled_at', name='uq_value_estimates_set_id_bucket_source_sampled_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('value_estimates')
    # ### end Alembic commands ###
