"""create lego_sets table

Revision ID: 9367555cbcd9
Revises: 
Create Date: 2026-07-30 23:18:46.340418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9367555cbcd9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lego_sets',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('number_variant', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('theme_group', sa.String(), nullable=True),
    sa.Column('subtheme', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('released', sa.Boolean(), nullable=False),
    sa.Column('pieces', sa.Integer(), nullable=True),
    sa.Column('minifigs', sa.Integer(), nullable=True),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('owned_by', sa.Integer(), nullable=True),
    sa.Column('wanted_by', sa.Integer(), nullable=True),
    sa.Column('retail_price_us', sa.Numeric(), nullable=True),
    sa.Column('rating', sa.Numeric(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(), nullable=True),
    sa.Column('barcode_ean', sa.String(), nullable=True),
    sa.Column('barcode_upc', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('set_id'),
    sa.UniqueConstraint('number', 'number_variant', name='uq_lego_sets_number_variant')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lego_sets')
    # ### end Alembic commands ###
