"""make condition nullable

Revision ID: ad9071f965a5
Revises: 0c26afd8599a
Create Date: 2026-08-15 01:14:55.290685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9071f965a5'
down_revision: Union[str, Sequence[str], None] = '0c26afd8599a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_listings', 'condition',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_listings', 'condition',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
