"""add api_call_log

Revision ID: ef30a04ddb86
Revises: 5823435d0ab2
Create Date: 2026-08-18 20:19:15.881427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef30a04ddb86'
down_revision: Union[str, Sequence[str], None] = '5823435d0ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api', sa.String(), nullable=False),
    sa.Column('count_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_call_log_api_count_expires_at', 'api_call_log', ['api', 'count_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_call_log_api_count_expires_at', table_name='api_call_log')
    op.drop_table('api_call_log')
    # ### end Alembic commands ###
